Ysmod 328 v2 informasjonsmodell
navikt/yrkesskade-saksbehandling-backend pull request #11
Opened 2022-08-22 10:43 UTC by olsnerik

2022-08-22 11:02 UTC, lurajon requested changes
Veldig bra jobbet! Noe flisespikkeri.

2022-08-22 11:02 UTC, lurajon commented on pom.xml
> -                                            <minimum>0.60</minimum>
Er det fordi det er mye genererte klasser som gjør at dekningsgraden går ned?

2022-08-22 11:02 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/BehandlingEntity.kt
> +    val saksbehandlingsansvarligIdent: String? = null,
Denne bør være var - slik at vi kan endre på den.

2022-08-22 11:02 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/BehandlingEntity.kt
> +    val status: Behandlingsstatus,
Dette er også en verdi som endres - byttes til var

2022-08-22 11:02 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/SakEntity.kt
> -    @Column(name = "bruker_fornavn", nullable = false)
Skal vi ta vare på de historiske verdiene her? En person kan ha skiftet navn etter en melding har blitt innsendt.

2022-08-22 11:02 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/hendelser/DokumentTilSaksbehandlingHendelseConsumerTest.kt
> +       // Thread.sleep(1000)
Denne kan vi ta bort

2022-08-22 11:02 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/hendelser/DokumentTilSaksbehandlingHendelseConsumerTest.kt
> +        //Mockito.verify(consumer, timeout(60000L).times(1)).listen(any())
Denne kan også fjernes

2022-08-22 11:46 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/BehandlingEntity.kt
> +    val saksbehandlingsansvarligIdent: String? = null,
Se bort fra denne kommentaren. Vi benytter oss heller av copy metoden som vi får fra data class

2022-08-22 11:46 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/BehandlingEntity.kt
> +    val status: Behandlingsstatus,
Se bort fra denne. Vi benytter copy og data class

2022-08-23 06:03 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/model/SakEntity.kt
> -    @Column(name = "bruker_fornavn", nullable = false)
Lurer på om sånt kan hentes i f.eks. PDL om man trenger historikk?

2022-08-23 06:24 UTC, merged