YSMOD-328
navikt/yrkesskade-saksbehandling-backend pull request #2
Opened 2022-05-20 08:13 UTC by lurajon

- Opprettet JPA entiteter for skademelding
- Opprettet repository og service for skademelding
- Opprettet graphql modell og tjeneste
- Opprettet tester for graphql og service

2022-05-20 10:10 UTC, olsnerik requested changes
Veldig bra utgangspunkt!

2022-05-20 10:10 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/hendelse/SkademeldingInnsendtHendelseConsumer.kt
> +            latch.countDown()
Hva gjør dette?

2022-05-20 10:10 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/graphql/model/SkademeldingPage.kt
> +import no.nav.yrkesskade.saksbehandling.skademelding.model.SkademeldingEntity
ubrukt import?

2022-05-20 10:10 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/BostedsAdressseEntity.kt
> +class BostedsAdressseEntity(
```suggestion
class BostedsAdresseEntity(
```

2022-05-20 10:10 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/BostedsAdressseEntity.kt
> +class BostedsAdressseEntity(
ser det er en del andre steder hvor det er tre S'er, håper det kan ordnes :P

2022-05-20 10:10 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/BostedsAdressseEntity.kt
> +    val skademelding: SkademeldingEntity?
trenger man tilgang til skademeldingen fra bostedsadressen? Eller er dette slik man gjør en join?

2022-05-20 10:10 UTC, olsnerik commented on pom.xml
> +            <groupId>io.mockk</groupId>
litt usikker på om denne er i bruk?

2022-05-20 10:10 UTC, olsnerik commented on src/main/resources/graphql/schemas/skademelding.graphqls
> +type Skademelding {
hva med hendelsesfakta og sånt? Eller er det noe vi evt. legger på etter hvert som det trengs, at dette er mer boilerplate/utgangspunkt å jobbe ut fra?

2022-05-20 10:10 UTC, olsnerik commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/test/AbstractTest.kt
> +@ExtendWith(SpringExtension::class)
denne er inkludert i `@SpringBootTest`

2022-05-20 10:10 UTC, olsnerik commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/test/docker/KafkaDockerContainer.kt
> +class KafkaDockerContainer private constructor() : KafkaContainer(DockerImageName.parse(IMAGE_NAME)) {
kult med container!

2022-05-20 11:05 UTC, erlendkri reviewed
Bra jobba! Har lagt til noen kommentarer...
Kult at du fikk til bruk av graphql!

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +    @Column(name = "hendelse_bakgrunn_ulykke", nullable = false)
Bakgrunn for ulykken er skjult for elev/student. KAn være null.

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/UlykkesstedEntity.kt
> +    val skademelding: SkademeldingEntity?
Trenger vi tilbakereferansen?

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/VirksomhetsAdresseEntity.kt
> +    val skademelding: SkademeldingEntity?
og denne?

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +
Har vi glemt antatt sykefravær?

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +
Skulle vi hatt med altinnrolleIDer?

2022-05-20 11:05 UTC, erlendkri commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/service/SkademeldingService.kt
> +            bostedsAdressse = null
bostedsadresse blir ikke mappet

2022-05-23 16:48 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/graphql/model/SkademeldingPage.kt
> +import no.nav.yrkesskade.saksbehandling.skademelding.model.SkademeldingEntity
Fikset!

2022-05-23 16:52 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/BostedsAdressseEntity.kt
> +class BostedsAdressseEntity(
Absolutt!! Må være tastaturlag....:P

2022-05-23 16:54 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/BostedsAdressseEntity.kt
> +    val skademelding: SkademeldingEntity?
Det er slik man må gjøre i en 1-til-1 join. Dette er fordi å kunne opprette entity i en one-shot uten å måtte hente primærnøkkel fra skamelding for deretter legge inn bostedsadresse.

2022-05-23 16:55 UTC, lurajon commented on pom.xml
> +            <groupId>io.mockk</groupId>
Det er den ikke. Fjerner den.

2022-05-23 16:56 UTC, lurajon commented on src/main/resources/graphql/schemas/skademelding.graphqls
> +type Skademelding {
Ja, det er tanken at vi bruker dette som en PoC og bygger videre.

2022-05-23 16:57 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/test/AbstractTest.kt
> +@ExtendWith(SpringExtension::class)
Stemmer! Jeg fikk ikke til graphql testene og glemte å fjerne denne.

2022-05-23 16:57 UTC, lurajon commented on src/test/kotlin/no/nav/yrkesskade/saksbehandling/test/docker/KafkaDockerContainer.kt
> +class KafkaDockerContainer private constructor() : KafkaContainer(DockerImageName.parse(IMAGE_NAME)) {
Tar heilt av!

2022-05-23 17:24 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +    @Column(name = "hendelse_bakgrunn_ulykke", nullable = false)
Ja, her måtte vi egentlig lage en til mange relasjon, siden det er flere årsaker og bakgrunner. Har endret.

2022-05-23 17:25 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/UlykkesstedEntity.kt
> +    val skademelding: SkademeldingEntity?
Vi trenger det for å kunne legge inn 1-til-1 relasjon i en og samme operasjon pga av skademelding_id er fremmed nøkkel i den andre tabellen.

2022-05-23 17:25 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/VirksomhetsAdresseEntity.kt
> +    val skademelding: SkademeldingEntity?
Samme som den andre

2022-05-23 17:30 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +
Det har vi! Jeg legger den til!

2022-05-23 17:32 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/model/SkademeldingEntity.kt
> +
Godt spørsmål! Jeg har alltid sett på innmelderrolle som noe som brukes for å sjekke om brukeren har lov til å legge inn skademelding. Vi viser den ikke i oppsummeringssiden og jeg vet heller ikke om den er relevant for saksbehandler. Dersom det blir aktuelt, så kan vi legge den til i ettertid

2022-05-23 17:35 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/skademelding/service/SkademeldingService.kt
> +            bostedsAdressse = null
Det stemmer! Jeg får ikke bostedsadresse ut fra noen av dataene fra skademeldinginnsendthendelse, så jeg har ikke mappet den. Jeg vil kanskje anta at vi bruker kafka streams til å ta en innsendt hendelse, legge på bostedsadresse, skadelidt navn osv og lage en ny kafka hendelse på en ny topic som vi konsumerer i saksbehandling

2022-05-30 07:36 UTC, lurajon commented
DB modell er feil.

2022-05-30 07:36 UTC, closed without merging