YSMOD-522
navikt/yrkesskade-saksbehandling-backend pull request #21
Opened 2022-09-01 07:19 UTC by lurajon

- lagt til funksjonalitet til å kunne ferdigstille en behandling via graphql
- utvidet tester

2022-09-01 09:32 UTC, olsnerik requested changes
Fint! Bare ett til felt som kanskje burde endres ved skriving til DB

2022-09-01 09:32 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +            saksbehandlingsansvarligIdent = autentisertBruker.preferredUsername
kom på at vi har også et endretAv-felt, som kanskje også burde oppdateres her? og i de andre operasjonene?

2022-09-05 07:19 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +            saksbehandlingsansvarligIdent = autentisertBruker.preferredUsername
Jeg har nå lagt på preferred username på dette feltet (kommer til å bli byttet til ident kanskje?)
endretAv vil alltid bli overskrevet og historikken vil ikke bli ivaretatt

2022-09-05 07:31 UTC, olsnerik approved these changes
Bra!

2022-09-05 08:22 UTC, merged