YSMOD-412 "brevutsending-utført" skal kun lagre utgående JPID, ikke sette ny status
navikt/yrkesskade-saksbehandling-backend pull request #55
Opened 2022-10-04 12:00 UTC by olsnerik

2022-10-04 12:12 UTC, lurajon requested changes

2022-10-04 12:12 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +    fun lagreUtgaaendeJournalpostFraBrevutsending(behandlingId: Long, journalpostId: String) {
Burde denne vært transactional?

2022-10-04 12:12 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +    fun lagreUtgaaendeJournalpostFraBrevutsending(behandlingId: Long, journalpostId: String) {
Dersom knytting feiler, men lagre behandling fungerer, er det da en "rett" status på denne?

2022-10-04 12:56 UTC, olsnerik commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +    fun lagreUtgaaendeJournalpostFraBrevutsending(behandlingId: Long, journalpostId: String) {
Vet ikke om jeg skjønner; vil ikke lagre behandling rulles tilbake hvis knytting feiler?

2022-10-05 10:37 UTC, lurajon commented on src/main/kotlin/no/nav/yrkesskade/saksbehandling/service/BehandlingService.kt
> +    fun lagreUtgaaendeJournalpostFraBrevutsending(behandlingId: Long, journalpostId: String) {
jo, dersom du har @Transactional - som lå i en annen klasse/metode

2022-10-05 10:37 UTC, lurajon approved these changes

2022-10-05 10:54 UTC, merged